### ISSUE TITLE
Make perl shebangs more portable

### ISSUE THREAD

**Issue by SoapGentoo** [mkuoppal/tiobench#6]
Using hardcoded perl shebangs is a problem for many kinds of systems, especially for Gentoo Prefix. In Gentoo, we currently patch the perl scripts:
https://github.com/gentoo/gentoo/blob/master/app-benchmarks/tiobench/files/tiobench-0.4.2-fix-perl-shebang.patch
Would you consider merging this patch, in order to make tiobench more portable to other kinds of systems. The rationale for relying on PATH/env lookup:
https://blogs.gentoo.org/mgorny/2016/02/08/a-quick-note-on-portable-shebangs/

**Comment by aliceinwire** [comment]
pr #11 close this issue.
